### ISSUE TITLE
Change "chest" armor to "torso" armor

### ISSUE THREAD

**Issue by mrpudn** [bamboo-black/ghosts-of-denth#14]
I've decided to use "torso" instead of "chest" for armor. Torso armor will protect the chest, shoulders, upper arms, and abdomen areas of the body.

**Comment by mrpudn** [comment]
@njgrisafi this might be a quick one to get you started with the project and get used to the codebase - thoughts?

**Comment by njgrisafi** [comment]
@mrpudn Yeah I can take this one!
